#===BUILD====##
FROM eclipse-temurin:25-jdk

LABEL authors="Nicolas-End"

#diz qual sera a pasta de trabalho
WORKDIR /SorveteriaApi

#copia todos os arquivos java para o workdir
COPY . .

CMD

EXPOSE 8080
